apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - name: frontend
        image: registry.digitalocean.com/deeptest/frontend:latest
        env:
          - name: PORT
            value: "3000"
        ports:
        - containerPort: 80


---


apiVersion: v1
kind: Service
metadata:
  name: frontend-deployment
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: frontend-deployment

